name: 'Build source distribution'
description: 'Build a Python source distribution using build and upload the resulting artifact'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      name: Install Python
      with:
        python-version: '3.9'

    - name: Install build tools
      shell: 'bash'
      run: python -m pip install build

    - name: Build sdist
      shell: 'bash'
      run: python -m build --sdist .


    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz
